---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: hero-mcp-hub-pg
    meta.helm.sh/release-namespace: business-test
  labels:
    app: hero-mcp-hub-pg
    app.kubernetes.io/managed-by: Helm
    chart: hero-chart-1.0.3
    heritage: Helm
    release: hero-mcp-hub-pg
  name: hero-mcp-hub-pg
  namespace: business-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hero-mcp-hub-pg
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2025-07-10T11:30:24+08:00'
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      creationTimestamp: null
      labels:
        app: hero-mcp-hub-pg
        pod-template-hash: 8975cdb85
        release: hero-mcp-hub-pg
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: yingxiong.com/work
                    operator: NotIn
                    values:
                      - nginx
      containers:
        - image: "pgvector/pgvector:pg17"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          name: "hero-mcp-hub-pg"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgvector-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgvector-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgvector-secret
                  key: postgres-db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: postgres-config
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: harbor-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: hero-mcp-hub-pg
    meta.helm.sh/release-namespace: business-test
  labels:
    app: hero-mcp-hub-pg
    app.kubernetes.io/managed-by: Helm
    chart: hero-chart-1.0.3
    heritage: Helm
    release: hero-mcp-hub-pg
    svcEndpoints: actuator
  name: hero-mcp-hub-pg
  namespace: business-test
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: hero-mcp-hub-pg
      port: 8888
      protocol: TCP
      targetPort: 5432
  selector:
    app: hero-mcp-hub-pg
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: hero-mcp-hub-pg
    meta.helm.sh/release-namespace: business-test
    nginx.ingress.kubernetes.io/hsts: 'false'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  labels:
    app: hero-mcp-hub-pg
    app.kubernetes.io/managed-by: Helm
    chart: hero-chart-1.0.3
    heritage: Helm
    release: hero-mcp-hub-pg
  name: hero-mcp-hub-pg
  namespace: business-test
spec:
  ingressClassName: nginx
  rules:
    - host: hero-mcp-hub-pg.huaweik3.yingxiong.com
      http:
        paths:
          - backend:
              service:
                name: hero-mcp-hub-pg
                port:
                  number: 8888
            path: /
            pathType: ImplementationSpecific

